#!/bin/sh
# Generate the boot-module hash manifest embedded in the kernel image.
#
# Usage: gen_module_manifest.sh <out-header> [<file>:<dest-path> ...]
#
# Each argument after the output path is one BOOT_MODULES pair, exactly as the
# boot.iso rule consumes it: the host file to ship, and the '/'-relative path the
# fs_server provisions it to in the store. For each pair we emit the destination
# path, the payload size, and the SHA-256 of the file's contents.
#
# The kernel compares every module GRUB hands it against this table before
# exposing it (see boot_module_verify_all in main.c). A module that is absent
# from the table, the wrong size, or the wrong hash is refused — so altering the
# ISO's module payloads no longer lets an attacker plant a root-owned binary in
# /bin, which is what audit finding A4 was about.
#
# With no pairs (the default build ships no modules) this writes an EMPTY table,
# and the kernel then refuses any module it is handed — fail closed, and exactly
# right: a kernel built without modules never attested to any.
#
# Output is deterministic (entries follow argument order, fixed formatting) so it
# does not disturb the reproducible build.
set -eu

out=$1
shift

tmp="$out.tmp$$"
# Keep a stray tmp file from surviving an interrupted build.
trap 'rm -f "$tmp"' EXIT INT TERM

{
    printf '/* GENERATED by tools/gen_module_manifest.sh -- do not edit.\n'
    printf ' *\n'
    printf ' * SHA-256 of every boot module shipped with this kernel, keyed by the\n'
    printf ' * destination path GRUB passes as the module cmdline. The kernel verifies\n'
    printf ' * each module against this table at boot and refuses any that does not\n'
    printf ' * match (audit A4). Empty when the build ships no modules.\n'
    printf ' */\n'
    printf '#ifndef HORUS_BOOT_MODULE_MANIFEST_H\n'
    printf '#define HORUS_BOOT_MODULE_MANIFEST_H\n\n'
    printf 'static const struct boot_module_digest BOOT_MODULE_DIGESTS[] = {\n'

    # ISO C has no empty-brace initialiser, so a module-free build still emits one
    # zero sentinel entry; BOOT_MODULE_DIGEST_COUNT below is 0 in that case, so the
    # kernel never reads it and every module it is handed is refused.
    if [ "$#" -eq 0 ]; then
        printf '    { "", 0u, {0} },   /* sentinel: this build ships no modules */\n'
    fi

    for pair in "$@"; do
        f=${pair%%:*}
        dest=${pair##*:}
        [ -f "$f" ] || { echo "gen_module_manifest: missing module file: $f" >&2; exit 1; }
        # `wc -c < file` avoids the filename in the output; sha256sum's first field
        # is the digest. Both are POSIX-portable enough for the build hosts we use.
        size=$(wc -c < "$f" | tr -d ' ')
        hash=$(sha256sum "$f" | cut -d' ' -f1)
        printf '    { "%s", %su, {' "$dest" "$size"
        # Emit the 32 digest bytes as 0x.. initialisers.
        i=0
        while [ "$i" -lt 64 ]; do
            byte=$(printf '%s' "$hash" | cut -c$((i + 1))-$((i + 2)))
            if [ "$i" -eq 0 ]; then printf '0x%s' "$byte"; else printf ',0x%s' "$byte"; fi
            i=$((i + 2))
        done
        printf '} },\n'
    done

    printf '};\n\n'
    printf '#define BOOT_MODULE_DIGEST_COUNT ((uint32_t)%su)\n\n' "$#"
    printf '#endif /* HORUS_BOOT_MODULE_MANIFEST_H */\n'
} > "$tmp"

# Only replace the header when the content actually changes, so an unchanged
# module set does not force a full kernel rebuild on every make invocation.
if [ -f "$out" ] && cmp -s "$tmp" "$out"; then
    rm -f "$tmp"
else
    mv "$tmp" "$out"
fi
