#!/bin/sh
# gen_libc_exports.sh -- the shared libc's export table, derived from what the
# programs actually reference.
#
# WHY DERIVED AND NOT A HAND-WRITTEN LIST. The table is the entire interface
# between a program and the shared libc: a symbol missing from it is a symbol no
# program can reach, and a symbol in it that nothing uses is library text every
# task maps for nobody. A list maintained by hand drifts from the programs in
# both directions at once, silently, and the only symptom is a link error much
# later or a page of dead code nobody notices.
#
# So the set is computed: every symbol the shipped programs leave undefined,
# intersected with every symbol newlib's libc.a defines. Measured 2026-08-29
# that is 59 of the 133 symbols the coreutils leave undefined -- the other 74
# are coreutils and gnulib internals, which are not libc and are not shared.
#
# ORDER IS THE ABI. Callers index this table, so a symbol's position is its
# identity. The list is sorted, which makes the output reproducible, and it also
# means INSERTING a symbol renumbers every later one: regenerate the callers'
# stubs from the same header or they will call the wrong function. That is the
# cost of an index-based interface and it is why real dynamic linking resolves
# by name. Stated here rather than discovered later.
#
# It emits TWO files: the table itself, and a header of index defines beside it
# (<out.c> with .c replaced by .h). Callers index the table, so a symbol's
# position IS its identity -- and a caller that hardcoded an index would be
# holding a copy of a fact this script owns. Both come from one run over one
# sorted list, so they cannot disagree about what is at slot n.
#
# Usage: gen_libc_exports.sh <libc.a> <out.c> <objects...>
set -eu

LIBC="$1"; shift
OUT="$1"; shift
OUT_H="${OUT%.c}.h"

[ -r "$LIBC" ] || { echo "gen_libc_exports: cannot read $LIBC" >&2; exit 1; }
[ $# -gt 0 ] || { echo "gen_libc_exports: no objects given" >&2; exit 1; }

TMP="$OUT.tmp.$$"
trap 'rm -f "$TMP.undef" "$TMP.def" "$TMP.data" "$TMP.need"' EXIT

# What the programs need but do not define.
nm --undefined-only "$@" 2>/dev/null | awk '{ print $2 }' | sort -u > "$TMP.undef"

# What libc defines, and which of those are writable data. The distinction is
# not cosmetic: a function is emitted as a function pointer, a data symbol as
# the address of an object, and getting it wrong makes the table hold the
# contents of a variable where its address belongs.
nm --defined-only "$LIBC" 2>/dev/null | awk '$2 ~ /^[TtWwRrDdBb]$/ { print $3 }' | sort -u > "$TMP.def"
# FUNCTIONS are T/t/W/w. Everything else defined -- R/r (rodata, e.g. _ctype_)
# and D/d/B/b (writable) -- is DATA. Classifying only the writable ones as data
# left `_ctype_`, a const array, declared as a function: the address taken is
# the same either way, so nothing broke, but a generated declaration that says
# the wrong kind of thing is a trap for whoever reads it next.
nm --defined-only "$LIBC" 2>/dev/null | awk '$2 !~ /^[TtWw]$/ { print $3 }' | sort -u > "$TMP.data"

comm -12 "$TMP.undef" "$TMP.def" > "$TMP.need"

COUNT=$(wc -l < "$TMP.need" | tr -d ' ')
[ "$COUNT" -gt 0 ] || {
	echo "gen_libc_exports: no libc symbols needed -- the object list is wrong" >&2
	exit 1
}

{
	echo "/* GENERATED by tools/gen_libc_exports.sh -- do not edit."
	echo " *"
	echo " * The shared libc's export table: every symbol the shipped programs leave"
	echo " * undefined that newlib's libc.a defines. Order is the ABI; see the script."
	echo " */"
	echo
	# Declared with types that match how each is USED, not its real prototype.
	# Only the ADDRESS is wanted here, and a mismatched prototype for a symbol
	# whose address is taken is still the right address -- but a function
	# declared as data (or the reverse) is not, which is why the two are split.
	while read -r sym; do
		[ -n "$sym" ] || continue
		if grep -qx "$sym" "$TMP.data"; then
			echo "extern char ${sym}[];"
		else
			echo "extern void ${sym}(void);"
		fi
	done < "$TMP.need"
	echo
	echo '__attribute__((section(".shlib_exports"), used))'
	echo "const void *const shlib_exports[$((COUNT + 1))] = {"
	while read -r sym; do
		[ -n "$sym" ] || continue
		echo "    (const void *)&${sym},"
	done < "$TMP.need"
	echo "    0"
	echo "};"
	echo
	echo "/* The count, for a caller that wants to check the table it found is the"
	echo " * table it was built against. */"
	echo "__attribute__((section(\".shlib_exports\"), used))"
	echo "const unsigned long shlib_export_count = ${COUNT}UL;"
} > "$TMP"

mv "$TMP" "$OUT"

# The index header. Written from the SAME sorted list, in the same pass, so the
# defines and the table cannot drift -- which is the whole reason a caller is
# given names instead of numbers.
{
	echo "/* GENERATED by tools/gen_libc_exports.sh -- do not edit."
	echo " *"
	echo " * Index of each symbol in the shared libc's export table. Order is the"
	echo " * ABI: inserting a symbol renumbers every later one, so a caller must be"
	echo " * rebuilt against the same generated pair, never against remembered"
	echo " * numbers. That is the cost of an index-based interface, and it is why a"
	echo " * real dynamic linker resolves by name."
	echo " */"
	echo "#ifndef HORUS_LIBC_EXPORTS_H"
	echo "#define HORUS_LIBC_EXPORTS_H"
	echo
	i=0
	while read -r sym; do
		[ -n "$sym" ] || continue
		# Not every libc symbol is a valid C identifier suffix on its own, but
		# every one here is -- nm gives us linker names, and a name that is not
		# an identifier could not have been referenced from C in the first place.
		echo "#define SHLIB_IDX_${sym}	${i}"
		i=$((i + 1))
	done < "$TMP.need"
	echo
	echo "#define SHLIB_EXPORT_COUNT	${COUNT}"
	echo "#endif"
} > "$OUT_H.tmp.$$"
mv "$OUT_H.tmp.$$" "$OUT_H"

echo "gen_libc_exports: $COUNT symbols -> $OUT, $OUT_H"
