#!/bin/sh
# gen_libc_stubs.sh -- one thunk per exported libc function.
#
# WHAT A PROGRAM LINKS AGAINST INSTEAD OF libc.a.
#
# There is no dynamic linker here, so a program cannot resolve `strlen` by name
# and have it bind to the shared library. What it can do is link against a stub
# that IS `strlen` and forwards: a tail jump through the library's export table,
# whose address the startup shim (userspace/shlib_start.c) fills in.
#
# WHY THE THUNKS ARE ASSEMBLY AND NOT C. A C forwarder needs the callee's
# prototype, and there are dozens of distinct signatures here -- including
# variadic ones, which a C forwarder cannot pass through at all without
# va_list-aware wrappers per function. A tail jump needs no prototype: the
# arguments are already in the right registers and on the stack, and the callee
# returns straight to the original caller.
#
# WHY %r11 AND NOT %rax, WHICH IS THE PART THAT BITES. The thunk needs one
# scratch register to hold the table pointer. %rax looks free -- it is
# caller-saved and never an argument register -- but in the x86-64 SysV ABI %al
# carries the NUMBER OF VECTOR REGISTERS used when calling a variadic function.
# Clobbering it tells printf how many xmm registers to spill.
#
# Measured rather than assumed, because the failure is silent most of the time:
# a table pointer whose low byte is >= 8 makes the callee save MORE registers
# than needed, which is harmless, so a %rax thunk passes every test until the
# table happens to land on an address ending in a small byte. Forced to zero, the
# same call segfaults. %r11 is caller-saved, never an argument register, and has
# no role in the variadic convention -- which is why a real PLT uses it too.
#
# DATA SYMBOLS GET NO STUB, and cannot. A tail jump forwards a CALL; a reference
# to a variable is an address the compiler emits directly, and redirecting it
# needs a GOT, which is what full dynamic linking provides. Programs therefore
# link only against the function half of the table:
#
#   _impure_ptr  works anyway, and is defined by the startup shim: it is a
#                POINTER to per-task state, so a program-local copy initialised
#                from the library still reaches the one struct _reent in the
#                library's own private data (S50).
#   optarg,      are the state itself. A program-local copy would DIVERGE from
#   optind       the library's getopt that writes it, so no stub is emitted and a
#                program that needs them fails to LINK -- which is the fail-closed
#                outcome, and better than a program whose optind silently stops
#                advancing. docs/LIMITATIONS.md 2.16.
#   _ctype_      is const, so a program-local copy would be correct, but it is
#                data all the same and gets no stub for the same reason.
#
# Usage: gen_libc_stubs.sh <exports.c> <out.S>
set -eu

EXPORTS="$1"
OUT="$2"

[ -r "$EXPORTS" ] || { echo "gen_libc_stubs: cannot read $EXPORTS" >&2; exit 1; }

TMP="$OUT.tmp.$$"
# Glob, not a name: a trap listing its temps individually goes stale the moment
# one is added after it, which is how five of gen_libc_exports.sh's reached main
# in #239. There is only one here today.
trap 'rm -f "$TMP" "$TMP".*' EXIT

# The generated table declares functions as `extern void sym(void);` and data as
# `extern char sym[];`, so the two are already distinguishable in the file that
# defines the ABI -- no second classification to drift from the first.
{
	echo "/* GENERATED by tools/gen_libc_stubs.sh from $EXPORTS -- do not edit."
	echo " *"
	echo " * One tail-jump thunk per exported libc FUNCTION. See the script for why"
	echo " * these are assembly, why the scratch register is %r11 and not %rax, and"
	echo " * why data symbols get no stub."
	echo " */"
	echo "	.text"
	echo

	idx=0
	while IFS= read -r line; do
		case "$line" in
		"extern void "*"(void);")
			sym=${line#extern void }
			sym=${sym%(void);}
			echo "	.globl	$sym"
			echo "	.type	$sym, @function"
			echo "$sym:"
			echo "	movq	__horus_shlib_table(%rip), %r11"
			echo "	jmpq	*($idx*8)(%r11)"
			echo "	.size	$sym, .-$sym"
			echo
			idx=$((idx + 1))
			;;
		"extern char "*"[];")
			# Data: occupies a table slot but gets no stub.
			idx=$((idx + 1))
			;;
		esac
	done < "$EXPORTS"

	echo "	.section .note.GNU-stack,\"\",@progbits"
} > "$TMP"

n=$(grep -c '^	.globl' "$TMP" || true)
[ "$n" -gt 0 ] || {
	echo "gen_libc_stubs: no function stubs emitted from $EXPORTS" >&2
	exit 1
}

mv "$TMP" "$OUT"
echo "gen_libc_stubs: $n function thunks -> $OUT"
