#!/bin/sh
# shlib_offsets.sh -- derive the shared library's layout from the object itself.
#
# WHY THIS EXISTS RATHER THAN THREE #defines. shlibtest.c and shlibpeer.c need
# to know where the export table is and which page is writable. Both facts are
# properties of userspace/shlibdemo.so, decided by the linker, and both used to
# be hardcoded: the export table was `SHLIB_VA + 0x4000` in two files. That was
# correct for exactly one layout. The moment shlib.ld split the object into a
# shared and a per-task segment the number moved, and a test that reads the
# wrong address does not fail honestly -- it reads whatever is there and reports
# on it.
#
# So the numbers are DERIVED from the object every build. A test that disagrees
# with the library it is testing is a test measuring something else.
#
# Usage: shlib_offsets.sh <shlibdemo.so> <out.h>
set -eu

SO="$1"
OUT="$2"

# The scratch below was removed by an explicit rm at the end and by nothing else,
# so `set -e` firing anywhere between creating it and that line leaked it into
# the tree. A trap covers every exit path; the glob covers temps added later.
# Same defect as gen_libc_exports.sh's, whose leaked scratch reached main in #239.
trap 'rm -f "$OUT".tmp.*' EXIT

[ -r "$SO" ] || { echo "shlib_offsets: cannot read $SO" >&2; exit 1; }

# e_entry carries the export table's address: a shared object has no entry point
# in the runnable sense, so -e shlib_exports puts it there. See shlib.c.
ENTRY=$(readelf -hW "$SO" | awk '/Entry point address:/ { print $NF }')
[ -n "$ENTRY" ] || { echo "shlib_offsets: no entry point in $SO" >&2; exit 1; }

# Highest page any PT_LOAD reaches, and the first page of the writable one.
# memsz, not filesz: .bss occupies no file bytes and is still writable data.
#
# The hex is converted in the SHELL, not in awk: mawk (the default awk on Debian,
# which is what CI runs) has no strtonum -- that is a gawk extension, and using
# it here failed with "function strtonum never defined" rather than producing a
# wrong number. awk selects fields; $(( )) parses them.
MAX=0
DATA_PAGE=-1
# readelf -lW LOAD lines: type offset vaddr paddr filesz memsz flags... align
# The flag column is one or two fields ("R E" vs "RW"), so everything between
# memsz and the trailing align is taken as the flags.
readelf -lW "$SO" | awk '$1 == "LOAD" {
        flags = "";
        for (i = 7; i < NF; i++) flags = flags $i;
        print $3, $6, flags
    }' > "$OUT.tmp.loads"

while read -r VADDR MEMSZ FLAGS; do
    [ -n "$VADDR" ] || continue
    V=$(( VADDR ))
    M=$(( MEMSZ ))
    HI=$(( V + M ))
    # An explicit if, not `[ ] && MAX=$HI`: under `set -e` an AND-OR list whose
    # last command does not run exits the script. It would have survived here
    # only because this object's segments happen to ascend.
    if [ "$HI" -gt "$MAX" ]; then MAX=$HI; fi
    case "$FLAGS" in
        *W*)
            P=$(( V / 4096 ))
            if [ "$DATA_PAGE" -lt 0 ] || [ "$P" -lt "$DATA_PAGE" ]; then DATA_PAGE=$P; fi
            ;;
    esac
done < "$OUT.tmp.loads"
rm -f "$OUT.tmp.loads"

PAGES=$(( (MAX + 4095) / 4096 ))

[ "$PAGES" -gt 0 ] || { echo "shlib_offsets: no PT_LOAD in $SO" >&2; exit 1; }
[ "$DATA_PAGE" -ge 0 ] || {
    echo "shlib_offsets: $SO has no writable segment; S50 has nothing to witness" >&2
    exit 1
}

cat > "$OUT" <<EOF
/* GENERATED by tools/shlib_offsets.sh from $SO -- do not edit.
 *
 * Derived rather than written down, because these are the linker's decisions
 * and a test holding a stale copy of them reads the wrong address and reports
 * on whatever it finds. */
#define SHLIB_EXPORTS_OFF  ${ENTRY}ULL
#define SHLIB_PAGES        ${PAGES}u
#define SHLIB_DATA_PAGE    ${DATA_PAGE}u
EOF
